<?php include "header.phtml"; ?>
<body>

    <?php include "nav.phtml"; ?>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below.

     -->
    <header class="intro-header" style="background-image: url('<?=$static_path?>img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <br/>
                        <!--
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                        -->

                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <?php if ($contents) { 
                    foreach ($contents as $val) {
                        $val = $val["_source"];
                ?>
                <div class="post-preview">
                    <a href="#">
                        <h2 class="post-title">
                        <?=$val["title"]?>
                        </h2>
                        <h3 class="post-subtitle">
                        <?=$val["content"]?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <?php } } ?>
                <!-- Pager -->
                <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&raquo;</a></li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <?php include "footer.phtml";?>

    <!--
        async属性表明这个文件需要异步加载，避免网页失去响应。
        IE不支持这个属性，只支持defer，所以把defer也写上
        defer async="true"
    <script src="<?=$static_path?>vendor/requirejs/require.js" data-main="<?=$static_path?>vendor/requirejs/main"></script>
    <script type="text/javascript">
        require(['jquery', 'bootstrap'], function ($) {
        });
    </script>

    <script src="<?=$static_path?>vendor/jquery/jquery.min.js"></script>
    <script src="<?=$static_path?>vendor/requirejs/require.js"></script>
    <script src="<?=$static_path?>vendor/bootstrap/js/bootstrap.min.js"></script>
    -->

    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="<?=$static_path?>js/jqBootstrapValidation.js"></script>
    <script src="<?=$static_path?>js/clean-blog.min.js"></script>

    <script src="https://cdn.bootcss.com/require.js/2.3.3/require.js"></script>
    <script src="<?=$static_path?>vendor/requirejs/main.js"></script>
    <script type="text/javascript">
        require(['index/index/index'], function(module) {
            module.init();
        });
    </script>

</body>

</html>
