    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/index/index">Start</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a type="button" data-toggle="modal" data-target="#myModal">search</a>
                    </li>
                    <li>
                        <a href="/index/index">Home</a>
                    </li>
                    <li>
                        <a href="/index/about">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="input-group">  
          <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
          <input type="text" id="search_input" class="form-control" placeholder="请输入关键字"/>  
          <!--
          <div data-handle="search" class="toolbar-handle input-group-addon btn-info">查找</div>  
          -->
       </div>  
      </div>
      <div id="search_contents" class="modal-body pre-scrollable" max-height="300px">
      </div>
    </div>
  </div>
</div>
